path:
  - 'C:/Program Files/LLVM/bin'
  - 'C:/Program Files/LLVM/lib'
  - 'C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64'
  - '/usr/lib/llvm-15/lib'
